### ISSUE TITLE
ng-submit conflict

### ISSUE THREAD

**Issue by lucasfernog** [mohbasheer/angular-chips#12]
With <chips> inside a form with ng-submit, when I press enter to add new chip (input chip-control), the form is submitted. I think it should steal the event somehow.

**Comment by mohbasheer** [comment]
Hi,

Please add the plnkr(https://plnkr.co/) or codepen(http://codepen.io/) example for your problem. I'll check and get back to you.

Thanks
Mohammed Basheer

**Comment by lucasfernog** [comment]
http://codepen.io/lucasfernog/pen/pEbYZW just type anything and press enter

**Comment by mohbasheer** [comment]
Got it.

**Comment by mohbasheer** [comment]
Resolved http://codepen.io/mohbasheer/pen/RGROAK?editors=1010

**Comment by mohbasheer** [comment]
Please take the latest build v1.0.8

**Comment by lucasfernog** [comment]
Thank you
