### ISSUE TITLE
npm integration

### ISSUE THREAD

**Issue by spajdo** [mohbasheer/angular-chips#18]
Please add npm integration.

**Comment by tareq89** [comment]
Please add npm integration!

**Comment by mohbasheer** [comment]
Registered with NPM. you can install now with  npm install angular-chips. please reopen if there is any issues.

**Comment by crbudzeak** [comment]
The NPM repository is behind in releases. NPM is at v1.0.9 whereas the current release of angular-chips is 1.0.11.

**Comment by mohbasheer** [comment]
I'll check thanks.

**Comment by mohbasheer** [comment]
Hi,

I just checked. NPM version is correct. it's 1.0.11.

https://github.com/mohbasheer/angular-chips/blob/v1.0.11/package.json

**Comment by crbudzeak** [comment]
When you browse NPM directly it shows 1.0.9 as the latest release.

[image: Inline image 2]


When you use NPM from the command line to install the module:

npm i angular-chips --save
> + angular-chips@1.0.9
> added 1 package in 1.059s


If you request 1.0.11 you get a no matching version error:

npm i angular-chips@1.0.11 --save
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for angular-chips@1.0.11
> npm ERR! notarget In most cases you or one of your dependencies are
> requesting
> npm ERR! notarget a package version that doesn't exist.



On Mon, Sep 18, 2017 at 10:24 AM, Mohammed Basheer <notifications@github.com

**Comment by mohbasheer** [comment]
Thanks man.

It's updated now.
