### ISSUE TITLE
Chip scope isn't accessible from template if model is instantiated as empty array (Angular 1.5+)

### ISSUE THREAD

**Issue by markvl91** [mohbasheer/angular-chips#2]
I'm unsure if this is an Angular issue or if this is something on angular-chips' side. I noticed when you instantiate the model to be used by angular-chips as an empty array, any new chips won't actually show their values. See http://codepen.io/anon/pen/ONBxPX. _Instant update_: after checking to verify, I noticed this is also the case when not assigning a model to be used at all, probably because you also substitute the model with an empty array.

I've personally worked around this by instantiating the array with values in it, and using timeout to wait one digest cycle before clearing the array again, like so:

```
    Archive.filterTypes = [''];
    $timeout(function() {
        Archive.filterTypes = [];
    });
```

It isn't pretty, but it works.

Hope this can get fixed!

**Comment by basheer-imaginea** [comment]
Hi Mark,

I am happy to see the first bug. thanks for creating this bug. I'll check and let you know very soon.

**Comment by mohbasheer** [comment]
Hi Mark,

I am happy to see the first bug. thanks for creating this bug. I'll check and let you know very soon.

**Comment by igorissen** [comment]
Same issue here

**Comment by mohbasheer** [comment]
Fixed. Please check the latest release v1.0.3

http://codepen.io/mohbasheer/pen/NNEaWr

**Comment by markvl91** [comment]
Only just got around to checking it out, works perfectly! Thanks for the effort.
