### ISSUE TITLE
Bug - Chips + Typeahead + Custom rendering doesn't clear fields

### ISSUE THREAD

**Issue by nathanmrtns** [mohbasheer/angular-chips#29]
Using angular-chips with typeahead enabled and custom rendering, after clicking on the suggestion it adds the chip but it doesn't clear the field.

I'm trying to use it on ionic 

This is basicaly what I'm doing (with a few differences) - http://codepen.io/anon/pen/rjjEqx

The image below is for you to visualize what I'm trying to say: 
- First I type my name, it gives me the suggestion with my full name and when I click on the suggestion it adds the chip but what I typed keeps there.

- Also there is this error: $digest already in progress (angular)

![screenshot from 2017-01-19 13-09-14](https://cloud.githubusercontent.com/assets/5864842/22114503/8091f3f4-de48-11e6-80ce-0e1c5b5fc7df.png)

**Comment by mohbasheer** [comment]
Hi, I just tried the example link it work fine. Pls check the attachment. I
tried in iPhone chrome browser. Could you tell me which browser and device
you tried?

**Comment by nathanmrtns** [comment]
Actually I'm working with IONIC, the printscreen is from its emulator. I think is something conflicting with ionic modules maybe.

**Comment by mohbasheer** [comment]
If you can try reproduce in codepen. Then it's easy to fix.

**Comment by nathanmrtns** [comment]
I tried here, but it works perfectly on codepen. When I run the app in my device (android) it complains about the $scope.apply function when addChip function is called. I'll be able to verify this tuesday. If you want to close the issue its ok.

**Comment by nathanmrtns** [comment]
I don't know if this is gonna help you but I fixed it here. As I said, it was something to do with the addChip function in the $scope.apply. It was throwing and exeption "$digest (or $apply) already in progress" then, I went into the addChip function and changed the scope.apply() for scope.$evalAsync(), or you can put scope.$apply inside a timeout()

It must have something to do with Ionic, I'm not sure.
