### ISSUE TITLE
CSS is not included when using automated build tools like yeoman's generator-gulp-angular

### ISSUE THREAD

**Issue by johnoscott** [mohbasheer/angular-chips#5]
When I use angular-chips with my front-end build tool the CSS is not automatically included.

I suggest adding support for front-end build tools.

The CSS must be present in the `main` section of `bower.json` for example:

```
  "main": [
    "./dist/angular-chips.js",
    "./dist/main.css"
  ],

```

More info about [how CSS and JavaScript of Bower modules are inejcted](https://github.com/Swiip/generator-gulp-angular/blob/master/docs/how-it-works.md#gulpinjectjs) 

Other modules I am using do reference their CSS in this manner, for example :

[Angular UI-Grid](https://github.com/angular-ui/bower-ui-grid/blob/master/bower.json)

**Comment by johnoscott** [comment]
I created  #4  with a solution.

**Comment by mohbasheer** [comment]
changes are merged. created new release version 1.0.4

**Comment by johnoscott** [comment]
Your bower.json file still shows version 1.0.3 for release 1.0.4

**Comment by mohbasheer** [comment]
Oops. I'll change it.

**Comment by mohbasheer** [comment]
It's done.  https://github.com/mohbasheer/angular-chips/tree/v1.0.5
