### ISSUE TITLE
angular 2 using chips 

### ISSUE THREAD

**Issue by karthikkavin** [mohbasheer/angular-chips#8]
Hi, I am start to learn angular 2. I have to use angular chips in angular 1**, but how to use angular 2 latest.

**Comment by mohbasheer** [comment]
Hi Karthik,

You can't use angular-chips in angular 2. I have to build a new one for
angular 2.

I'll let you know the plan as soon as possible. Thanks for checking with me.

Regards
Mohammed Basheer
